from sqlalchemy import Column, Integer, String, Float, DateTime, Index
from .base import Base, TimestampMixin

class Transaction(TimestampMixin, Base):
    __tablename__ = 'transactions'
    id = Column(Integer, primary_key=True, autoincrement=True)
    amc_code = Column(String, nullable=True)
    folio_no = Column(String, nullable=True)
    prodcode = Column(String, nullable=True)
    scheme = Column(String, nullable=True)
    inv_name = Column(String, nullable=True)
    trxntype = Column(String, nullable=True)
    trxnno = Column(Integer, nullable=True)
    trxnmode = Column(String, nullable=True)
    trxnstat = Column(String, nullable=True)
    usercode = Column(String, nullable=True)
    usrtrxno = Column(String, nullable=True)
    traddate = Column(DateTime, nullable=True)
    postdate = Column(DateTime, nullable=True)
    purprice = Column(Float, nullable=True)
    units = Column(Float, nullable=True)
    amount = Column(Float, nullable=True)
    brokcode = Column(String, nullable=True)
    subbrok = Column(String, nullable=True)
    brokperc = Column(Float, nullable=True)
    brokcomm = Column(Float, nullable=True)
    altfolio = Column(String, nullable=True)
    rep_date = Column(DateTime, nullable=True)
    time1 = Column(String, nullable=True)
    trxnsubtyp = Column(String, nullable=True)
    application_no = Column(String, nullable=True)
    trxn_nature = Column(String, nullable=True)
    tax = Column(Float, nullable=True)
    total_tax = Column(Float, nullable=True)
    te_15h = Column(String, nullable=True)
    micr_no = Column(String, nullable=True)
    remarks = Column(String, nullable=True)
    swflag = Column(String, nullable=True)
    old_folio = Column(String, nullable=True)
    seq_no = Column(String, nullable=True)
    reinvest_flag = Column(String, nullable=True)
    mult_brok = Column(String, nullable=True)
    stt = Column(Float, nullable=True)
    location = Column(String, nullable=True)
    scheme_type = Column(String, nullable=True)
    tax_status = Column(String, nullable=True)
    load = Column(Float, nullable=True)
    scanrefno = Column(String, nullable=True)
    pan = Column(String, nullable=True)
    inv_iin = Column(String, nullable=True)
    targ_src_scheme = Column(String, nullable=True)
    trxn_type_flag = Column(String, nullable=True)
    ticob_trtype = Column(String, nullable=True)
    ticob_trno = Column(String, nullable=True)
    ticob_posted_date = Column(DateTime, nullable=True)  
    dp_id = Column(String, nullable=True)
    trxn_charges = Column(Float, nullable=True)
    eligib_amt = Column(Float, nullable=True)
    src_of_txn = Column(String, nullable=True)
    trxn_suffix = Column(String, nullable=True)
    siptrxnno = Column(String, nullable=True)
    ter_location = Column(String, nullable=True)
    euin = Column(String, nullable=True)
    euin_valid = Column(String, nullable=True)
    euin_opted = Column(String, nullable=True)
    sub_brk_arn = Column(String, nullable=True)
    exch_dc_flag = Column(String, nullable=True)
    src_brk_code = Column(String, nullable=True)
    sys_regn_date = Column(DateTime, nullable=True)  
    ac_no = Column(String, nullable=True)
    bank_name = Column(String, nullable=True)
    reversal_code = Column(String, nullable=True)
    exchange_flag = Column(String, nullable=True)
    ca_initiated_date = Column(DateTime, nullable=True)  
    gst_state_code = Column(String, nullable=True)
    igst_amount = Column(Float, nullable=True)
    cgst_amount = Column(Float, nullable=True)
    sgst_amount = Column(Float, nullable=True)
    rev_remark = Column(String, nullable=True)
    original_trxnno = Column(String, nullable=True)
    stamp_duty = Column(Float, nullable=True)
    folio_old = Column(String, nullable=True)
    scheme_folio_number = Column(String, nullable=True)
    amc_ref_no = Column(String, nullable=True)
    request_ref_no = Column(String, nullable=True)

    __table_args__ = (
        Index('ix_transactions_folio_no', 'folio_no'),
        Index('ix_transactions_trxnno', 'trxnno'),
        Index('ix_transactions_usercode', 'usercode'),
    )