"""Initial migration

Revision ID: fc9c7d7e4181
Revises: 
Create Date: 2025-05-28 22:43:57.815671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9c7d7e4181'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amc_code', sa.String(), nullable=True),
    sa.Column('folio_no', sa.String(), nullable=True),
    sa.Column('prodcode', sa.String(), nullable=True),
    sa.Column('scheme', sa.String(), nullable=True),
    sa.Column('inv_name', sa.String(), nullable=True),
    sa.Column('trxntype', sa.String(), nullable=True),
    sa.Column('trxnno', sa.Integer(), nullable=True),
    sa.Column('trxnmode', sa.String(), nullable=True),
    sa.Column('trxnstat', sa.String(), nullable=True),
    sa.Column('usercode', sa.String(), nullable=True),
    sa.Column('usrtrxno', sa.String(), nullable=True),
    sa.Column('traddate', sa.DateTime(), nullable=True),
    sa.Column('postdate', sa.DateTime(), nullable=True),
    sa.Column('purprice', sa.Float(), nullable=True),
    sa.Column('units', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('brokcode', sa.String(), nullable=True),
    sa.Column('subbrok', sa.String(), nullable=True),
    sa.Column('brokperc', sa.Float(), nullable=True),
    sa.Column('brokcomm', sa.Float(), nullable=True),
    sa.Column('altfolio', sa.String(), nullable=True),
    sa.Column('rep_date', sa.DateTime(), nullable=True),
    sa.Column('time1', sa.String(), nullable=True),
    sa.Column('trxnsubtyp', sa.String(), nullable=True),
    sa.Column('application_no', sa.String(), nullable=True),
    sa.Column('trxn_nature', sa.String(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('total_tax', sa.Float(), nullable=True),
    sa.Column('te_15h', sa.String(), nullable=True),
    sa.Column('micr_no', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('swflag', sa.String(), nullable=True),
    sa.Column('old_folio', sa.String(), nullable=True),
    sa.Column('seq_no', sa.String(), nullable=True),
    sa.Column('reinvest_flag', sa.String(), nullable=True),
    sa.Column('mult_brok', sa.String(), nullable=True),
    sa.Column('stt', sa.Float(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('scheme_type', sa.String(), nullable=True),
    sa.Column('tax_status', sa.String(), nullable=True),
    sa.Column('load', sa.Float(), nullable=True),
    sa.Column('scanrefno', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('inv_iin', sa.String(), nullable=True),
    sa.Column('targ_src_scheme', sa.String(), nullable=True),
    sa.Column('trxn_type_flag', sa.String(), nullable=True),
    sa.Column('ticob_trtype', sa.String(), nullable=True),
    sa.Column('ticob_trno', sa.String(), nullable=True),
    sa.Column('ticob_posted_date', sa.DateTime(), nullable=True),
    sa.Column('dp_id', sa.String(), nullable=True),
    sa.Column('trxn_charges', sa.Float(), nullable=True),
    sa.Column('eligib_amt', sa.Float(), nullable=True),
    sa.Column('src_of_txn', sa.String(), nullable=True),
    sa.Column('trxn_suffix', sa.String(), nullable=True),
    sa.Column('siptrxnno', sa.String(), nullable=True),
    sa.Column('ter_location', sa.String(), nullable=True),
    sa.Column('euin', sa.String(), nullable=True),
    sa.Column('euin_valid', sa.String(), nullable=True),
    sa.Column('euin_opted', sa.String(), nullable=True),
    sa.Column('sub_brk_arn', sa.String(), nullable=True),
    sa.Column('exch_dc_flag', sa.String(), nullable=True),
    sa.Column('src_brk_code', sa.String(), nullable=True),
    sa.Column('sys_regn_date', sa.DateTime(), nullable=True),
    sa.Column('ac_no', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('reversal_code', sa.String(), nullable=True),
    sa.Column('exchange_flag', sa.String(), nullable=True),
    sa.Column('ca_initiated_date', sa.DateTime(), nullable=True),
    sa.Column('gst_state_code', sa.String(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('rev_remark', sa.String(), nullable=True),
    sa.Column('original_trxnno', sa.String(), nullable=True),
    sa.Column('stamp_duty', sa.Float(), nullable=True),
    sa.Column('folio_old', sa.String(), nullable=True),
    sa.Column('scheme_folio_number', sa.String(), nullable=True),
    sa.Column('amc_ref_no', sa.String(), nullable=True),
    sa.Column('request_ref_no', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_folio_no', 'transactions', ['folio_no'], unique=False)
    op.create_index('ix_transactions_trxnno', 'transactions', ['trxnno'], unique=False)
    op.create_index('ix_transactions_usercode', 'transactions', ['usercode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_usercode', table_name='transactions')
    op.drop_index('ix_transactions_trxnno', table_name='transactions')
    op.drop_index('ix_transactions_folio_no', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
