from pydantic import BaseModel
from typing import Optional
from datetime import datetime


class TransactionSchema(BaseModel):
    amc_code: Optional[str]
    folio_no: Optional[str]
    prodcode: Optional[str]
    scheme: Optional[str]
    inv_name: Optional[str]
    trxntype: Optional[str]
    trxnno: Optional[int]
    trxnmode: Optional[str]
    trxnstat: Optional[str]
    usercode: Optional[str]
    usrtrxno: Optional[str]
    traddate: Optional[datetime]
    postdate: Optional[datetime]
    purprice: Optional[float]
    units: Optional[float]
    amount: Optional[float]
    brokcode: Optional[str]
    subbrok: Optional[str]
    brokperc: Optional[float]
    brokcomm: Optional[float]
    altfolio: Optional[str]
    rep_date: Optional[datetime]
    time1: Optional[str]
    trxnsubtyp: Optional[str]
    application_no: Optional[str]
    trxn_nature: Optional[str]
    tax: Optional[float]
    total_tax: Optional[float]
    te_15h: Optional[str]
    micr_no: Optional[str]
    remarks: Optional[str]
    swflag: Optional[str]
    old_folio: Optional[str]
    seq_no: Optional[str]
    reinvest_flag: Optional[str]
    mult_brok: Optional[str]
    stt: Optional[float]
    location: Optional[str]
    scheme_type: Optional[str]
    tax_status: Optional[str]
    load: Optional[float]
    scanrefno: Optional[str]
    pan: Optional[str]
    inv_iin: Optional[str]
    targ_src_scheme: Optional[str]
    trxn_type_flag: Optional[str]
    ticob_trtype: Optional[str]
    ticob_trno: Optional[str]
    ticob_posted_date: Optional[datetime]
    dp_id: Optional[str]
    trxn_charges: Optional[float]
    eligib_amt: Optional[float]
    src_of_txn: Optional[str]
    trxn_suffix: Optional[str]
    siptrxnno: Optional[str]
    ter_location: Optional[str]
    euin: Optional[str]
    euin_valid: Optional[str]
    euin_opted: Optional[str]
    sub_brk_arn: Optional[str]
    exch_dc_flag: Optional[str]
    src_brk_code: Optional[str]
    sys_regn_date: Optional[datetime]
    ac_no: Optional[str]
    bank_name: Optional[str]
    reversal_code: Optional[str]
    exchange_flag: Optional[str]
    ca_initiated_date: Optional[datetime]
    gst_state_code: Optional[str]
    igst_amount: Optional[float]
    cgst_amount: Optional[float]
    sgst_amount: Optional[float]
    rev_remark: Optional[str]
    original_trxnno: Optional[str]
    stamp_duty: Optional[float]
    folio_old: Optional[str]
    scheme_folio_number: Optional[str]
    amc_ref_no: Optional[str]
    request_ref_no: Optional[str]

    model_config = {"from_attributes": True}


class TransactionPaginatedResponse(BaseModel):
    items: list[TransactionSchema]
    total: int
